[package]
name = "cutemarket"
version = "1.0.0"
authors = []

[addresses]
cutemarket = "0xf28e42120ec3007579f530ac426b2d553f501681431a433f3584bf6d37c94f16"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

